### ISSUE TITLE
Remove COMDAT support in the next release

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/ar_archive_writer#22]
According to https://github.com/rust-lang/ar_archive_writer/pull/20#issuecomment-2295292772 it turns out that it isn't actually supported by the linker after all.

**Comment by ChrisDenton** [comment]
I've taken a simpler approach in https://github.com/ChrisDenton/ar_archive_writer/commit/a5b424a6ef9d6416b299ac27c2dba224e2470253 which I've more thoroughly tested as working. Not PRing it yet unless/until https://github.com/rust-lang/rust/pull/129257 comes back green.

If that works, we can probably just rename the flag to something more generic without breaking the interface (I used `whole_archive_compat` in my experiment).

**Comment by bjorn3** [comment]
Forgot to pull before I published... Published as v0.4.2. The commit for v0.4.1 has been orphaned, but is still available under the v0.4.1 tag.

https://github.com/rust-lang/ar_archive_writer/issues/21 would have helped avoid this.

**Comment by ChrisDenton** [comment]
Ah thanks!
