### ISSUE TITLE
Add support for creating COFF archives

### ISSUE THREAD

**Issue by dpaoliello** [rust-lang/ar_archive_writer#9]
Currently COFF is not supported:
https://github.com/rust-lang/ar_archive_writer/blob/master/src/archive_writer.rs#L42

However, we need to build rlibs as COFF for MSVC when using LLVM as a backend so that LLVM generates symbol tables: https://github.com/rust-lang/rust/pull/123467

**Comment by bjorn3** [comment]
LLVM added support for them last year. Ar_archive_writer will need to adopt all changes since the commit it was derived from.
